name: avanzza
description: Avanzza 2.0 app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4

  # Auth Federada
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^6.0.3

  # Isar community
  isar_community: ^3.1.0+1
  isar_community_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # Codegen
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Utils
  equatable: ^2.0.5
  collection: ^1.18.0
  mobile_scanner: ^3.5.6
  uuid: ^4.0.0
  dropdown_button2: ^2.3.9
  google_mlkit_barcode_scanning: ^0.14.1
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.2.0
  camera: ^0.11.1 #TODO(10/11/2025) Actualizar a la mÃ¡s reciente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.9.0
  freezed: ^3.1.0
  isar_community_generator: ^3.1.0+1

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/campaign/
