name: avanzza
description: Avanzza 2.0 app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.3

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4

  # Isar community
  isar_community: ^3.1.0+1
  isar_community_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # Codegen
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Utils
  intl: ^0.20.2
  equatable: ^2.0.5
  collection: ^1.18.0
  mobile_scanner: ^3.5.6
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.9.0
  freezed: ^3.1.0
  isar_community_generator: ^3.1.0+1

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/campaign/
